apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: {{ .Values.appName  | quote }}
spec:
  replicas: {{ .Values.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName  | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName  | quote }}
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80