apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ .Values.appName  | quote }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.appName  | quote }}
