name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || contains(github.head_ref, 'branch-name/') || (github.event_name == 'workflow_dispatch')
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y make gcc g++ git