name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && contains(github.head_ref, 'branch-name/')) || (github.event_name == 'workflow_dispatch')
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "test"