name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push') || contains(github.head_ref, 'branch-name/') || (github.event_name == 'workflow_dispatch')
    - name: Install & build
      run: |
        echo "Deploy code..."